### ISSUE TITLE
Feature#005 Función que devuelva el menor de los datos de la colección en la clase DecimalCollection

### ISSUE THREAD

**Issue by ricardossmadrid** [ricardossmadrid/ricardoSanchezSPAIEcp2#5]
· Hay que crear una función que devuelva el valor del dato más pequeño de la colección.
· Hacer test que lo verifique.

Más info en la wiki:
https://github.com/ricardossmadrid/ricardoSanchezSPAIEcp2/wiki/Mejoras-clase-DecimalCollection

Cualquier duda la comentamos.

Muchas gracias

**Comment by GameEngineers** [comment]
Buenas tardes Ricardo,
He añadido las ampliaciones de esta mejora. También queria decirte que me he tomado la "libertad" de añadir al .gitignore una linea para evitar que se suba una carpeta /Scripts/ que me he creado a fin de poder añadir un script de test para realizar pruebas en local antes de hacer merge con develop. Espero que te parezca bien!. 
Un saludo.
