### ISSUE TITLE
Feature#006 Función que elimine el último dato de la colección, en la clase DecimalCollection

### ISSUE THREAD

**Issue by ricardossmadrid** [ricardossmadrid/ricardoSanchezSPAIEcp2#6]
· Función que elimine el dato que se encuentra en la última posición de la lista.
· Hacer test que lo compruebe.

Más info en la wiki:
https://github.com/ricardossmadrid/ricardoSanchezSPAIEcp2/wiki/Mejoras-clase-DecimalCollection

Cualquier duda la comentamos.

Muchas gracias

**Comment by GameEngineers** [comment]
La mejora se ha creado correctamente.
Un saludo.
