### ISSUE TITLE
Feature#008 Crear función isEquivalente en la clase Fraction

### ISSUE THREAD

**Issue by ricardossmadrid** [ricardossmadrid/ricardoSanchezSPAIEcp2#8]
· Hay que crear la clase isEquivalente para la clase Fraction
· Crear el test correspondiente.

Más info en la wiki:
https://github.com/ricardossmadrid/ricardoSanchezSPAIEcp2/wiki/Mejoras-clase-Fraction

SI hay dudas las comentamos

Muchas gracias

**Comment by GameEngineers** [comment]
Mejora realizada correctamente.
